apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kdnk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kdnk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kdnk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kdnk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kdnk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nvle-tenant/rhtap-demo-app/hacbs-test-project-kdnk@sha256:6ff0a7f9cbf34e9a652ce0f24d18ed9851fe30a45e11fae49d7d000e5c66eb4f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
